### PR TITLE
Make ingress annotations configurable

### LINKED ISSUE #108: Feature: Allow injection of annotations for the Ingress
## Feature Description

To be able to use the chart in my K8s cluster, I need to be able to add new annotations, my cluster using cert-manager.

## Proposed Solution

Add a list of annotations for the Ingress which would be injected in the Ingress file

## Additional Information

Any additional information or context that may be helpful in implementing the feature.

### PR DESCRIPTION
**Pull request by ridoo**
Closes #108

## Description

Replaces `geonode.ingress.addNginxIngressAnnotation` with `geonode.ingress.annotations` to give the user more flexibility in configuring the ingress.

@AlexGacon Are you able to test [this feature branch](https://github.com/zalf-rdm/geonode-k8s/tree/issue%23108_allow-injection-of-annotations-for-the-ingress) and if it adds what you are looking for?

## Type of Change

Please select the relevant option:

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update
- [ ] Refactoring
- [ ] Other (please describe)

## Related Issue

If there is an existing issue related to this pull request, please reference it here.

closes #

## Checklist

Please ensure that your pull request meets the following requirements:

- The pull request is limited to one type (docs, feature, bug fix, etc.)
- The pull request is as small as possible. Consider opening multiple pull requests instead of one large one.
- The feature or bug fix has been discussed and documented in an issue beforehand.

## Additional Notes

Any additional information or context regarding the pull request can be provided here.

Thank you for creating this pull request

### CODE REVIEW

**Comment by mwallschlaeger** [comment]
I like the idea of this PR making annotations more general. this PR should include update for the nginx ingress docs (https://github.com/zalf-rdm/geonode-k8s/blob/main/docs/nginx-ingress-class.md).  

As this PR would break update current installations, I would add some information into the changelog, when releasing a new version

**Comment by ridoo** [comment]
> I like the idea of this PR making annotations more general. this PR should include update for the nginx ingress docs (https://github.com/zalf-rdm/geonode-k8s/blob/main/docs/nginx-ingress-class.md).
> 
> As this PR would break update current installations, I would add some information into the changelog, when releasing a new version

Cool, I will update the docs then.

**Review by mwallschlaeger — CHANGES_REQUESTED** [review]
the PR looks good so far. Could you increase release version like described in https://github.com/zalf-rdm/geonode-k8s/wiki/Release-Checklist I) so we could increase chart version directly with this PR

**Comment by AlexGacon** [comment]
@mwallschlaeger do you have an idea when you could do a release with the new PRs ?

**Comment by mwallschlaeger** [comment]
@AlexGacon I will check your other PR now. If the PR will work out I gonna merge PR #113  and afterwards this one.

**Review by mwallschlaeger — APPROVED** [review]

**Pull request merged**
